package com.example.demo.model;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.EMP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private Integer empCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.EMP_NM
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String empNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.GENDER_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String genderCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.JOIN_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.POSITION_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String positionCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.DUTY_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String dutyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.ROLE_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String roleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.ASSIGNED_TASK
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String assignedTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.EMAIL
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.ZIP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String zipCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.ADDRESS1
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.ADDRESS2
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.IMAGE_PATH
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.CREATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_member.UPDATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.EMP_CD
     *
     * @return the value of sp_member.EMP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public Integer getEmpCd() {
        return empCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.EMP_CD
     *
     * @param empCd the value for sp_member.EMP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setEmpCd(Integer empCd) {
        this.empCd = empCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.EMP_NM
     *
     * @return the value of sp_member.EMP_NM
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getEmpNm() {
        return empNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.EMP_NM
     *
     * @param empNm the value for sp_member.EMP_NM
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setEmpNm(String empNm) {
        this.empNm = empNm == null ? null : empNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.GENDER_CD
     *
     * @return the value of sp_member.GENDER_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getGenderCd() {
        return genderCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.GENDER_CD
     *
     * @param genderCd the value for sp_member.GENDER_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setGenderCd(String genderCd) {
        this.genderCd = genderCd == null ? null : genderCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.JOIN_DATE
     *
     * @return the value of sp_member.JOIN_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.JOIN_DATE
     *
     * @param joinDate the value for sp_member.JOIN_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setJoinDate(String joinDate) {
        this.joinDate = joinDate == null ? null : joinDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.POSITION_CD
     *
     * @return the value of sp_member.POSITION_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getPositionCd() {
        return positionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.POSITION_CD
     *
     * @param positionCd the value for sp_member.POSITION_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setPositionCd(String positionCd) {
        this.positionCd = positionCd == null ? null : positionCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.DUTY_CD
     *
     * @return the value of sp_member.DUTY_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getDutyCd() {
        return dutyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.DUTY_CD
     *
     * @param dutyCd the value for sp_member.DUTY_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setDutyCd(String dutyCd) {
        this.dutyCd = dutyCd == null ? null : dutyCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.ROLE_CD
     *
     * @return the value of sp_member.ROLE_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getRoleCd() {
        return roleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.ROLE_CD
     *
     * @param roleCd the value for sp_member.ROLE_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setRoleCd(String roleCd) {
        this.roleCd = roleCd == null ? null : roleCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.ASSIGNED_TASK
     *
     * @return the value of sp_member.ASSIGNED_TASK
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getAssignedTask() {
        return assignedTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.ASSIGNED_TASK
     *
     * @param assignedTask the value for sp_member.ASSIGNED_TASK
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setAssignedTask(String assignedTask) {
        this.assignedTask = assignedTask == null ? null : assignedTask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.EMAIL
     *
     * @return the value of sp_member.EMAIL
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.EMAIL
     *
     * @param email the value for sp_member.EMAIL
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.ZIP_CD
     *
     * @return the value of sp_member.ZIP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getZipCd() {
        return zipCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.ZIP_CD
     *
     * @param zipCd the value for sp_member.ZIP_CD
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setZipCd(String zipCd) {
        this.zipCd = zipCd == null ? null : zipCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.ADDRESS1
     *
     * @return the value of sp_member.ADDRESS1
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.ADDRESS1
     *
     * @param address1 the value for sp_member.ADDRESS1
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.ADDRESS2
     *
     * @return the value of sp_member.ADDRESS2
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.ADDRESS2
     *
     * @param address2 the value for sp_member.ADDRESS2
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.IMAGE_PATH
     *
     * @return the value of sp_member.IMAGE_PATH
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.IMAGE_PATH
     *
     * @param imagePath the value for sp_member.IMAGE_PATH
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.CREATED_DATE
     *
     * @return the value of sp_member.CREATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.CREATED_DATE
     *
     * @param createdDate the value for sp_member.CREATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_member.UPDATED_DATE
     *
     * @return the value of sp_member.UPDATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_member.UPDATED_DATE
     *
     * @param updatedDate the value for sp_member.UPDATED_DATE
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}