package com.example.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public MemberExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmpCdIsNull() {
            addCriterion("EMP_CD is null");
            return (Criteria) this;
        }

        public Criteria andEmpCdIsNotNull() {
            addCriterion("EMP_CD is not null");
            return (Criteria) this;
        }

        public Criteria andEmpCdEqualTo(Integer value) {
            addCriterion("EMP_CD =", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdNotEqualTo(Integer value) {
            addCriterion("EMP_CD <>", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdGreaterThan(Integer value) {
            addCriterion("EMP_CD >", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_CD >=", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdLessThan(Integer value) {
            addCriterion("EMP_CD <", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_CD <=", value, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdIn(List<Integer> values) {
            addCriterion("EMP_CD in", values, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdNotIn(List<Integer> values) {
            addCriterion("EMP_CD not in", values, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdBetween(Integer value1, Integer value2) {
            addCriterion("EMP_CD between", value1, value2, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpCdNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_CD not between", value1, value2, "empCd");
            return (Criteria) this;
        }

        public Criteria andEmpNmIsNull() {
            addCriterion("EMP_NM is null");
            return (Criteria) this;
        }

        public Criteria andEmpNmIsNotNull() {
            addCriterion("EMP_NM is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNmEqualTo(String value) {
            addCriterion("EMP_NM =", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmNotEqualTo(String value) {
            addCriterion("EMP_NM <>", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmGreaterThan(String value) {
            addCriterion("EMP_NM >", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_NM >=", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmLessThan(String value) {
            addCriterion("EMP_NM <", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmLessThanOrEqualTo(String value) {
            addCriterion("EMP_NM <=", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmLike(String value) {
            addCriterion("EMP_NM like", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmNotLike(String value) {
            addCriterion("EMP_NM not like", value, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmIn(List<String> values) {
            addCriterion("EMP_NM in", values, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmNotIn(List<String> values) {
            addCriterion("EMP_NM not in", values, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmBetween(String value1, String value2) {
            addCriterion("EMP_NM between", value1, value2, "empNm");
            return (Criteria) this;
        }

        public Criteria andEmpNmNotBetween(String value1, String value2) {
            addCriterion("EMP_NM not between", value1, value2, "empNm");
            return (Criteria) this;
        }

        public Criteria andGenderCdIsNull() {
            addCriterion("GENDER_CD is null");
            return (Criteria) this;
        }

        public Criteria andGenderCdIsNotNull() {
            addCriterion("GENDER_CD is not null");
            return (Criteria) this;
        }

        public Criteria andGenderCdEqualTo(String value) {
            addCriterion("GENDER_CD =", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdNotEqualTo(String value) {
            addCriterion("GENDER_CD <>", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdGreaterThan(String value) {
            addCriterion("GENDER_CD >", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER_CD >=", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdLessThan(String value) {
            addCriterion("GENDER_CD <", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdLessThanOrEqualTo(String value) {
            addCriterion("GENDER_CD <=", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdLike(String value) {
            addCriterion("GENDER_CD like", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdNotLike(String value) {
            addCriterion("GENDER_CD not like", value, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdIn(List<String> values) {
            addCriterion("GENDER_CD in", values, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdNotIn(List<String> values) {
            addCriterion("GENDER_CD not in", values, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdBetween(String value1, String value2) {
            addCriterion("GENDER_CD between", value1, value2, "genderCd");
            return (Criteria) this;
        }

        public Criteria andGenderCdNotBetween(String value1, String value2) {
            addCriterion("GENDER_CD not between", value1, value2, "genderCd");
            return (Criteria) this;
        }

        public Criteria andJoinDateIsNull() {
            addCriterion("JOIN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andJoinDateIsNotNull() {
            addCriterion("JOIN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andJoinDateEqualTo(String value) {
            addCriterion("JOIN_DATE =", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotEqualTo(String value) {
            addCriterion("JOIN_DATE <>", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateGreaterThan(String value) {
            addCriterion("JOIN_DATE >", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateGreaterThanOrEqualTo(String value) {
            addCriterion("JOIN_DATE >=", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateLessThan(String value) {
            addCriterion("JOIN_DATE <", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateLessThanOrEqualTo(String value) {
            addCriterion("JOIN_DATE <=", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateLike(String value) {
            addCriterion("JOIN_DATE like", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotLike(String value) {
            addCriterion("JOIN_DATE not like", value, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateIn(List<String> values) {
            addCriterion("JOIN_DATE in", values, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotIn(List<String> values) {
            addCriterion("JOIN_DATE not in", values, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateBetween(String value1, String value2) {
            addCriterion("JOIN_DATE between", value1, value2, "joinDate");
            return (Criteria) this;
        }

        public Criteria andJoinDateNotBetween(String value1, String value2) {
            addCriterion("JOIN_DATE not between", value1, value2, "joinDate");
            return (Criteria) this;
        }

        public Criteria andPositionCdIsNull() {
            addCriterion("POSITION_CD is null");
            return (Criteria) this;
        }

        public Criteria andPositionCdIsNotNull() {
            addCriterion("POSITION_CD is not null");
            return (Criteria) this;
        }

        public Criteria andPositionCdEqualTo(String value) {
            addCriterion("POSITION_CD =", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdNotEqualTo(String value) {
            addCriterion("POSITION_CD <>", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdGreaterThan(String value) {
            addCriterion("POSITION_CD >", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION_CD >=", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdLessThan(String value) {
            addCriterion("POSITION_CD <", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdLessThanOrEqualTo(String value) {
            addCriterion("POSITION_CD <=", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdLike(String value) {
            addCriterion("POSITION_CD like", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdNotLike(String value) {
            addCriterion("POSITION_CD not like", value, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdIn(List<String> values) {
            addCriterion("POSITION_CD in", values, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdNotIn(List<String> values) {
            addCriterion("POSITION_CD not in", values, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdBetween(String value1, String value2) {
            addCriterion("POSITION_CD between", value1, value2, "positionCd");
            return (Criteria) this;
        }

        public Criteria andPositionCdNotBetween(String value1, String value2) {
            addCriterion("POSITION_CD not between", value1, value2, "positionCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdIsNull() {
            addCriterion("DUTY_CD is null");
            return (Criteria) this;
        }

        public Criteria andDutyCdIsNotNull() {
            addCriterion("DUTY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDutyCdEqualTo(String value) {
            addCriterion("DUTY_CD =", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdNotEqualTo(String value) {
            addCriterion("DUTY_CD <>", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdGreaterThan(String value) {
            addCriterion("DUTY_CD >", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdGreaterThanOrEqualTo(String value) {
            addCriterion("DUTY_CD >=", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdLessThan(String value) {
            addCriterion("DUTY_CD <", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdLessThanOrEqualTo(String value) {
            addCriterion("DUTY_CD <=", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdLike(String value) {
            addCriterion("DUTY_CD like", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdNotLike(String value) {
            addCriterion("DUTY_CD not like", value, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdIn(List<String> values) {
            addCriterion("DUTY_CD in", values, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdNotIn(List<String> values) {
            addCriterion("DUTY_CD not in", values, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdBetween(String value1, String value2) {
            addCriterion("DUTY_CD between", value1, value2, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andDutyCdNotBetween(String value1, String value2) {
            addCriterion("DUTY_CD not between", value1, value2, "dutyCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdIsNull() {
            addCriterion("ROLE_CD is null");
            return (Criteria) this;
        }

        public Criteria andRoleCdIsNotNull() {
            addCriterion("ROLE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andRoleCdEqualTo(String value) {
            addCriterion("ROLE_CD =", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotEqualTo(String value) {
            addCriterion("ROLE_CD <>", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdGreaterThan(String value) {
            addCriterion("ROLE_CD >", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_CD >=", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLessThan(String value) {
            addCriterion("ROLE_CD <", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLessThanOrEqualTo(String value) {
            addCriterion("ROLE_CD <=", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdLike(String value) {
            addCriterion("ROLE_CD like", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotLike(String value) {
            addCriterion("ROLE_CD not like", value, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdIn(List<String> values) {
            addCriterion("ROLE_CD in", values, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotIn(List<String> values) {
            addCriterion("ROLE_CD not in", values, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdBetween(String value1, String value2) {
            addCriterion("ROLE_CD between", value1, value2, "roleCd");
            return (Criteria) this;
        }

        public Criteria andRoleCdNotBetween(String value1, String value2) {
            addCriterion("ROLE_CD not between", value1, value2, "roleCd");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskIsNull() {
            addCriterion("ASSIGNED_TASK is null");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskIsNotNull() {
            addCriterion("ASSIGNED_TASK is not null");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskEqualTo(String value) {
            addCriterion("ASSIGNED_TASK =", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskNotEqualTo(String value) {
            addCriterion("ASSIGNED_TASK <>", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskGreaterThan(String value) {
            addCriterion("ASSIGNED_TASK >", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIGNED_TASK >=", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskLessThan(String value) {
            addCriterion("ASSIGNED_TASK <", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskLessThanOrEqualTo(String value) {
            addCriterion("ASSIGNED_TASK <=", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskLike(String value) {
            addCriterion("ASSIGNED_TASK like", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskNotLike(String value) {
            addCriterion("ASSIGNED_TASK not like", value, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskIn(List<String> values) {
            addCriterion("ASSIGNED_TASK in", values, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskNotIn(List<String> values) {
            addCriterion("ASSIGNED_TASK not in", values, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskBetween(String value1, String value2) {
            addCriterion("ASSIGNED_TASK between", value1, value2, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andAssignedTaskNotBetween(String value1, String value2) {
            addCriterion("ASSIGNED_TASK not between", value1, value2, "assignedTask");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andZipCdIsNull() {
            addCriterion("ZIP_CD is null");
            return (Criteria) this;
        }

        public Criteria andZipCdIsNotNull() {
            addCriterion("ZIP_CD is not null");
            return (Criteria) this;
        }

        public Criteria andZipCdEqualTo(String value) {
            addCriterion("ZIP_CD =", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotEqualTo(String value) {
            addCriterion("ZIP_CD <>", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdGreaterThan(String value) {
            addCriterion("ZIP_CD >", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP_CD >=", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLessThan(String value) {
            addCriterion("ZIP_CD <", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLessThanOrEqualTo(String value) {
            addCriterion("ZIP_CD <=", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLike(String value) {
            addCriterion("ZIP_CD like", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotLike(String value) {
            addCriterion("ZIP_CD not like", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdIn(List<String> values) {
            addCriterion("ZIP_CD in", values, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotIn(List<String> values) {
            addCriterion("ZIP_CD not in", values, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdBetween(String value1, String value2) {
            addCriterion("ZIP_CD between", value1, value2, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotBetween(String value1, String value2) {
            addCriterion("ZIP_CD not between", value1, value2, "zipCd");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNull() {
            addCriterion("ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNotNull() {
            addCriterion("ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress1EqualTo(String value) {
            addCriterion("ADDRESS1 =", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotEqualTo(String value) {
            addCriterion("ADDRESS1 <>", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThan(String value) {
            addCriterion("ADDRESS1 >", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 >=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThan(String value) {
            addCriterion("ADDRESS1 <", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 <=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Like(String value) {
            addCriterion("ADDRESS1 like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotLike(String value) {
            addCriterion("ADDRESS1 not like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1In(List<String> values) {
            addCriterion("ADDRESS1 in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotIn(List<String> values) {
            addCriterion("ADDRESS1 not in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Between(String value1, String value2) {
            addCriterion("ADDRESS1 between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotBetween(String value1, String value2) {
            addCriterion("ADDRESS1 not between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNull() {
            addCriterion("ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNotNull() {
            addCriterion("ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress2EqualTo(String value) {
            addCriterion("ADDRESS2 =", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotEqualTo(String value) {
            addCriterion("ADDRESS2 <>", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThan(String value) {
            addCriterion("ADDRESS2 >", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 >=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThan(String value) {
            addCriterion("ADDRESS2 <", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 <=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Like(String value) {
            addCriterion("ADDRESS2 like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotLike(String value) {
            addCriterion("ADDRESS2 not like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2In(List<String> values) {
            addCriterion("ADDRESS2 in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotIn(List<String> values) {
            addCriterion("ADDRESS2 not in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Between(String value1, String value2) {
            addCriterion("ADDRESS2 between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotBetween(String value1, String value2) {
            addCriterion("ADDRESS2 not between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNull() {
            addCriterion("IMAGE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNotNull() {
            addCriterion("IMAGE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andImagePathEqualTo(String value) {
            addCriterion("IMAGE_PATH =", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotEqualTo(String value) {
            addCriterion("IMAGE_PATH <>", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThan(String value) {
            addCriterion("IMAGE_PATH >", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_PATH >=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThan(String value) {
            addCriterion("IMAGE_PATH <", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_PATH <=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLike(String value) {
            addCriterion("IMAGE_PATH like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotLike(String value) {
            addCriterion("IMAGE_PATH not like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathIn(List<String> values) {
            addCriterion("IMAGE_PATH in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotIn(List<String> values) {
            addCriterion("IMAGE_PATH not in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathBetween(String value1, String value2) {
            addCriterion("IMAGE_PATH between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotBetween(String value1, String value2) {
            addCriterion("IMAGE_PATH not between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterionForJDBCDate("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterionForJDBCDate("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("UPDATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("UPDATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATED_DATE <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATED_DATE in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATED_DATE not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATED_DATE between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATED_DATE not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sp_member
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 12 11:20:21 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}