package com.example.demo.mapper;

import com.example.demo.model.Member;
import com.example.demo.model.MemberExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int deleteByPrimaryKey(Integer empCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int insert(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int insertSelective(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    Member selectByPrimaryKey(Integer empCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Member row, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int updateByExample(@Param("row") Member row, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int updateByPrimaryKeySelective(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_member
     *
     * @mbg.generated Thu Oct 12 11:20:21 ICT 2023
     */
    int updateByPrimaryKey(Member row);
}